DROP TABLE IF EXISTS lute_credits CASCADE;
DROP TABLE IF EXISTS lute_tracks CASCADE;
DROP TABLE IF EXISTS lute_albums CASCADE;
DROP TABLE IF EXISTS lute_artists CASCADE;
DROP TABLE IF EXISTS lute_albums_artists CASCADE;