version: "3"

tasks:
  "protoc:gen:web":
    internal: true
    cmds:
      - docker run --rm -v {{.TASKFILE_DIR}}/proto:/proto -v {{.OUTPUT_DIR}}:/out namely/protoc-all -d /proto -o /out -l web

  "core:build":
    dir: core
    env:
      RUST_LOG: warn,core=debug,lute-postgres-connector=debug
    cmds:
      - cargo build

  "core:run":
    dir: core
    env:
      RUST_LOG: warn,core=debug,lute-postgres-connector=debug
    cmds:
      - cargo run

  "core:lint":
    dir: core
    cmds:
      - cargo clippy
  
  "core:lint:fix":
    dir: core
    env:
      RUST_LOG: warn,core=debug,lute-postgres-connector=debug
    cmds:
      - cargo clippy --fix --allow-dirty

  "core:fmt":
    dir: core
    cmds:
      - cargo fmt

  "web:proto":
    cmds:
      - task: "protoc:gen:web"
        vars:
          OUTPUT_DIR: "{{.TASKFILE_DIR}}/web/src/proto"

  "web:run":
    deps: ["web:proto"]
    dir: web
    cmds:
      - npm start

  "web:build":
    deps: ["web:proto"]
    dir: web
    cmds:
      - rm -rf ./dist
      - npm i
      - npm run build
  
  "web:fmt":
    dir: web
    cmds:
      - npm run fmt

  "extension:proto":
    cmds:
      - task: "protoc:gen:web"
        vars:
          OUTPUT_DIR: "{{.TASKFILE_DIR}}/extension/src/proto"

  "extension:build":
    deps: ["extension:proto"]
    dir: extension
    cmds:
      - rm -rf ./dist
      - npm i
      - npm run build

  "proto":
    cmds:
      - task: "web:proto"
      - task: "extension:proto"

  "build":
    cmds:
      - task: "core:build"
      - task: "web:build"
      - task: "extension:build"

  "fmt":
    cmds:
      - task: "core:fmt"
      - task: "web:fmt"
        
  "redis:up":
    cmds:
      - docker-compose -f ./infra/dev/redis.docker-compose.yml up -d
  
  "openobserve:up":
    cmds:
      - docker-compose -f ./infra/dev/openobserve/docker-compose.yml up -d
  
  "openobserve:down":
    cmds:
      - docker-compose -f ./infra/dev/openobserve/docker-compose.yml down

  "core:up:openobserve":
    cmds:
      - docker-compose -f ./infra/dev/redis.docker-compose.yml -f ./infra/dev/openobserve/docker-compose.yml up -d
      - task: "core:run"
  
  "core:up":
    cmds:
      - task: "redis:up"
      - task: "core:run" 

  "postgres:up":
    cmds:
      - docker-compose -f ./infra/dev/postgres.docker-compose.yml up -d
  
  "pg-connector:run":
    dir: connector/postgres
    cmds:
      - cargo run -- --postgres-url postgres://lute:password@localhost:25432/lute --subscriber-id dev-pg-connector --stream-id replication
  
  "pg-connector:up":
    cmds:
      - task: "postgres:up"
      - task: "pg-connector:run"

  "memgraph:up":
    cmds:
      - docker-compose -f ./infra/dev/memgraph.docker-compose.yml up -d
  
  "bolt-connector:run":
    dir: connector/bolt
    cmds:
      - cargo run -- --subscriber-id dev-mg-connector --stream-id parser --db-name memgraph
  
  "bolt-connector:up":
    cmds:
      - task: "memgraph:up"
      - task: "bolt-connector:run"