CREATE TABLE lute_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id VARCHAR NOT NULL,
  stream_id VARCHAR NOT NULL,
  payload JSONB NOT NULL,
  event_timestamp BIGINT NOT NULL,
  saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_lute_events_payload ON lute_events USING gin(payload);
CREATE UNIQUE INDEX idx_lute_events_entry_id_stream_id ON lute_events (entry_id, stream_id);