CREATE TABLE lute_artists (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name VARCHAR NOT NULL UNIQUE,
  name VARCHAR NOT NULL
);
CREATE INDEX idx_lute_artists_file_name ON lute_artists (file_name);